import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

const Post2 = () => (
	<Layout>
		<SEO title="The Post" />
		<h1>The Post</h1>
		<p className="postBody">Meditation gentrify fam, yuccie kickstarter brunch vape. Pitchfork freegan biodiesel bicycle rights. Semiotics flexitarian four loko XOXO raw denim chartreuse. Cray ramps microdosing everyday carry bicycle rights vexillologist. Bitters bushwick schlitz, 3 wolf moon tofu hoodie beard bicycle rights truffaut keffiyeh sartorial. Affogato coloring book glossier humblebrag hella godard pour-over fashion axe leggings tote bag af. Lomo neutra vape keytar man bun. Pabst fanny pack meggings, gochujang deep v stumptown banjo flexitarian poke hoodie. Jianbing iceland seitan echo park, tacos literally cornhole poke pinterest blue bottle man bun. Intelligentsia affogato freegan quinoa cray. Banjo bicycle rights quinoa, meditation pork belly brooklyn tumeric thundercats adaptogen portland vape art party. Cloud bread four loko ramps woke, la croix artisan poke tbh kale chips cornhole snackwave lo-fi normcore meditation.</p>
		<p className="postBody">Health goth raw denim vaporware waistcoat, vegan neutra glossier. Cronut chartreuse tbh meh schlitz. Snackwave lumbersexual pinterest narwhal, single-origin coffee coloring book selfies tacos. Fanny pack vaporware disrupt health goth, organic snackwave heirloom jean shorts truffaut lo-fi stumptown. Gluten-free semiotics vice activated charcoal gochujang cloud bread. Lomo authentic messenger bag polaroid flannel butcher occupy offal helvetica wolf skateboard jean shorts. Polaroid echo park raw denim freegan. Irony twee tattooed craft beer small batch. Copper mug brooklyn crucifix hashtag deep v chicharrones ethical vegan pabst disrupt. Cardigan shabby chic hell of, lomo actually letterpress vape four dollar toast mixtape prism salvia edison bulb. Brunch raw denim heirloom banh mi.</p>
		<p className="postBody">Deep v hammock post-ironic edison bulb everyday carry disrupt. Art party viral occupy af tote bag before they sold out. Affogato before they sold out gochujang aesthetic literally pitchfork. Typewriter ennui banjo, mumblecore selfies succulents helvetica you probably haven’t heard of them celiac live-edge. Photo booth hell of migas skateboard. Heirloom pinterest DIY, vaporware subway tile gentrify meh. Snackwave glossier viral gastropub poutine williamsburg poke. Ethical messenger bag readymade direct trade organic locavore pabst. Quinoa selvage cardigan, banjo vaporware af food truck. Stumptown gochujang lyft tousled shoreditch lumbersexual. Cliche ugh kinfolk plaid shaman.</p>
		<p className="postBody">Beard glossier pok pok before they sold out, chicharrones brunch edison bulb brooklyn schlitz cardigan 90’s stumptown. Distillery man bun chicharrones cold-pressed swag. Fanny pack knausgaard dreamcatcher kickstarter try-hard cred sriracha glossier cloud bread pork belly VHS williamsburg meggings etsy. 90’s subway tile photo booth, +1 farm-to-table hot chicken hammock dreamcatcher migas chia hoodie. Paleo swag craft beer selfies kale chips, pok pok neutra yuccie lo-fi irony. Kitsch 8-bit air plant, truffaut leggings cloud bread lomo 90’s. Fixie brunch blue bottle, hashtag cred coloring book listicle. Bespoke flexitarian plaid, kickstarter edison bulb leggings coloring book cred poke. Heirloom direct trade cold-pressed freegan prism chia retro migas slow-carb mumblecore church-key 3 wolf moon XOXO tbh tattooed.</p>
		<p className="postBody">XOXO vaporware 3 wolf moon skateboard, shaman affogato meditation irony mixtape letterpress. Live-edge listicle yr, meggings four dollar toast drinking vinegar crucifix truffaut vape retro microdosing ugh jean shorts biodiesel palo santo. 8-bit pour-over +1 man braid raclette whatever. Keytar aesthetic master cleanse, letterpress heirloom brunch squid VHS truffaut helvetica hoodie taiyaki DIY. Hell of listicle before they sold out fashion axe cronut schlitz la croix tofu VHS street art intelligentsia occupy. Fingerstache paleo tote bag heirloom synth. Umami stumptown meditation literally marfa, salvia tofu bicycle rights blog pinterest. Vinyl shoreditch organic copper mug, mlkshk lomo readymade typewriter tofu biodiesel selfies butcher poutine ugh brooklyn. Hoodie affogato fanny pack banjo thundercats. Kickstarter af art party vexillologist fanny pack yuccie. Bushwick letterpress microdosing drinking vinegar marfa. Seitan deep v vape chartreuse, keytar messenger bag cloud bread try-hard. Kombucha bicycle rights everyday carry yr, slow-carb poutine hammock chia keffiyeh edison bulb. Tilde vice next level leggings church-key, biodiesel ramps migas echo park taiyaki distillery ugh. Venmo viral chartreuse banjo raclette kinfolk vape roof party franzen.</p>
	<Link to="/blog">Go back to the blog page</Link>
</Layout>
)

export default Post2
